-- Insert Genres
INSERT INTO genres (genre_name) VALUES
('Literary Fiction'),
('Science Fiction'),
('Fantasy'),
('Mystery'),
('Thriller/Suspense'),
('Horror'),
('Romance'),
('Historical Fiction'),
('Adventure'),
('Chick Lit/Womens Fiction'),
('Crime/Detective'),
('Paranormal/Supernatural'),
('Biography/Autobiography'),
('Memoir'),
('Self-Help'),
('History'),
('Travel'),
('Essay/Reflection'),
('True Crime'),
('Philosophy'),
('Psychology'),
('Science/Nature'),
('Health & Wellness'),
('Cooking/Food'),
('Business/Finance'),
('Parenting/Family'),
('Religion/Spirituality'),
('Politics/Government'),
('Art/Photography'),
('Sports'),
('Technology'),
('Poetry'),
('Drama'),
('Graphic Novels/Comics'),
('Anthologies/Short Stories');

-- Insert States
INSERT INTO states (name) VALUES
('Alabama'),
('Alaska'),
('Arizona'),
('Arkansas'),
('California'),
('Colorado'),
('Connecticut'),
('Delaware'),
('Florida'),
('Georgia'),
('Hawaii'),
('Idaho'),
('Illinois'),
('Indiana'),
('Iowa'),
('Kansas'),
('Kentucky'),
('Louisiana'),
('Maine'),
('Maryland'),
('Massachusetts'),
('Michigan'),
('Minnesota'),
('Mississippi'),
('Missouri'),
('Montana'),
('Nebraska'),
('Nevada'),
('New Hampshire'),
('New Jersey'),
('New Mexico'),
('New York'),
('North Carolina'),
('North Dakota'),
('Ohio'),
('Oklahoma'),
('Oregon'),
('Pennsylvania'),
('Rhode Island'),
('South Carolina'),
('South Dakota'),
('Tennessee'),
('Texas'),
('Utah'),
('Vermont'),
('Virginia'),
('Washington'),
('West Virginia'),
('Wisconsin'),
('Wyoming');